services:
  client:
    container_name: onboarding-client-container
    image: onboarding-client-image
    build:
      context: ./onboarding-ui
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - onboarding_network

  backend:
    container_name: onboarding-back-container
    image: onboarding-back-image
    build:
      context: ./onboarding-api
    ports:
      - "8080:8080"
    env_file:
      - ./onboarding-api/.env
    depends_on:
      - database
    networks:
      - onboarding_network

  database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: onboarding
    ports:
      - "5432:5432"
    networks:
      - onboarding_network

networks:
  onboarding_network:
    driver: bridge
